In [1]:
import numpy as np
import keras

Using TensorFlow backend.


In [2]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPool2D, Flatten, Dense, Dropout
from keras.optimizers import adam
from keras.preprocessing import image 
from keras.preprocessing.image import ImageDataGenerator

In [3]:
classifier = Sequential()

classifier.add(Conv2D(filters = 32, kernel_size = (3,3), input_shape = (64,64,3), activation = "relu"))
classifier.add(Dropout(0.2))

classifier.add(MaxPool2D(pool_size = (2,2)))

classifier.add(Conv2D(filters = 32, kernel_size = (3,3), activation = "relu"))
classifier.add(Dropout(0.2))

classifier.add(MaxPool2D(pool_size = (2,2)))
classifier.add(Flatten())

classifier.add(Dense(units = 80, activation = "relu"))
classifier.add(Dropout(0.2))

classifier.add(Dense(units = 1, activation = "sigmoid"))

classifier.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])

In [4]:
# image agumentation using keras image data generator

train_datsgen = ImageDataGenerator(rescale = 1./255)
test_datagen = ImageDataGenerator(rescale = 1./255)

In [5]:
training_set = train_datsgen.flow_from_directory("data\\train", target_size= (64,64), class_mode= "binary")

Found 2000 images belonging to 2 classes.


In [6]:
test_set = train_datsgen.flow_from_directory("data\\test", target_size= (64,64),class_mode= "binary")

Found 600 images belonging to 2 classes.


In [7]:
# creating checkpoints

from keras.callbacks import ModelCheckpoint

filepath = "checkpoints\\weights-improvement-{epoch:02d}-{loss: .4f}.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor= "loss", verbose = 1, save_best_only= True, mode= "min")
callbacks_list = [checkpoint]


In [9]:
# training the model 

classifier.fit_generator(training_set, epochs = 15, steps_per_epoch=2000, validation_data= test_set, validation_steps=600, callbacks = callbacks_list)

Epoch 1/15
2000/2000 [==============================] - 620s 310ms/step - loss: 0.1445 - accuracy: 0.9373 - val_loss: 1.6597 - val_accuracy: 0.7028

Epoch 00001: loss improved from inf to 0.14451, saving model to checkpoints\weights-improvement-01- 0.1445.hdf5
Epoch 2/15
2000/2000 [==============================] - 590s 295ms/step - loss: 0.0118 - accuracy: 0.9966 - val_loss: 1.1947 - val_accuracy: 0.6887

Epoch 00002: loss improved from 0.14451 to 0.01187, saving model to checkpoints\weights-improvement-02- 0.0119.hdf5
Epoch 3/15
2000/2000 [==============================] - 616s 308ms/step - loss: 0.0105 - accuracy: 0.9970 - val_loss: 1.7005 - val_accuracy: 0.6946

Epoch 00003: loss improved from 0.01187 to 0.01054, saving model to checkpoints\weights-improvement-03- 0.0105.hdf5
Epoch 4/15
2000/2000 [==============================] - 577s 288ms/step - loss: 0.0072 - accuracy: 0.9977 - val_loss: 2.0285 - val_accuracy: 0.6882

Epoch 00004: loss improved from 0.01054 to 0.00719, saving m

In [103]:
test_set1 = test_datagen.flow_from_directory("data\\testing", target_size= (64,64), class_mode= None, shuffle=False)

Found 200 images belonging to 2 classes.


In [104]:
test_set1.reset()

In [105]:
pred = classifier.predict_generator(test_set1)

In [106]:
pred

array([[1.92224979e-05],
       [2.01000571e-02],
       [2.08616257e-07],
       [6.23655319e-03],
       [1.10333264e-02],
       [2.78118253e-03],
       [1.49011612e-07],
       [5.04225492e-04],
       [1.09630823e-02],
       [7.83033073e-01],
       [6.51881814e-01],
       [1.37290955e-02],
       [0.00000000e+00],
       [4.27663326e-04],
       [6.49777055e-03],
       [0.00000000e+00],
       [0.00000000e+00],
       [2.24709511e-05],
       [4.85739410e-02],
       [9.96267259e-01],
       [5.21993041e-02],
       [9.99984622e-01],
       [9.71687376e-01],
       [0.00000000e+00],
       [1.06599331e-02],
       [4.85991359e-01],
       [9.67315912e-01],
       [1.96099281e-03],
       [9.99061108e-01],
       [4.76837158e-07],
       [9.99995947e-01],
       [0.00000000e+00],
       [0.00000000e+00],
       [1.00135803e-05],
       [8.94069672e-08],
       [9.99999523e-01],
       [9.99603093e-01],
       [9.99997556e-01],
       [0.00000000e+00],
       [1.23582482e-02],


In [146]:
predicted_class = (pred > 0.5)*1

In [147]:
predicted_class = predicted_class.reshape(1,-1)[0]
predicted_class

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1])

In [148]:
actual_class = test_set1.classes
actual_class

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [150]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(actual_class, predicted_class))

[[73 27]
 [36 64]]


In [151]:
print(classification_report(actual_class, predicted_class))

              precision    recall  f1-score   support

           0       0.67      0.73      0.70       100
           1       0.70      0.64      0.67       100

    accuracy                           0.69       200
   macro avg       0.69      0.69      0.68       200
weighted avg       0.69      0.69      0.68       200

